export const places = [
  {
    id: 'canoa-quebrada',
    name: 'Canoa Quebrada',
    region: 'Litoral Leste',
    city: 'Aracati',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85',
    description: 'Falésias, jangadas e histórias construídas entre o mar e a vila.',
    longDescription: 'Entre falésias avermelhadas e o Atlântico, Canoa Quebrada preserva modos de vida ligados à pesca, ao artesanato e à memória de uma vila que acolhe o mundo sem perder o sotaque cearense.',
    tags: ['Praia', 'Artesanato', 'Memória'],
    photos: 24,
  },
  {
    id: 'fortaleza',
    name: 'Fortaleza',
    region: 'Capital',
    city: 'Fortaleza',
    image: 'https://images.unsplash.com/photo-1596395819057-e37f55a8516b?auto=format&fit=crop&w=1200&q=85',
    description: 'Patrimônio, música, arte urbana e encontros à beira-mar.',
    longDescription: 'A capital reúne muitas camadas do Ceará: mercados populares, centros culturais, ocupações artísticas, festas tradicionais e uma produção contemporânea que se renova todos os dias.',
    tags: ['Música', 'Patrimônio', 'Arte'],
    photos: 31,
  },
  {
    id: 'guaramiranga',
    name: 'Guaramiranga',
    region: 'Maciço de Baturité',
    city: 'Guaramiranga',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85',
    description: 'Serra, café, teatro e tradições em meio à mata atlântica.',
    longDescription: 'O clima serrano envolve uma cidade marcada por festivais, casarões, cultivo de café e narrativas de famílias que mantêm viva a cultura do Maciço de Baturité.',
    tags: ['Serra', 'Teatro', 'Gastronomia'],
    photos: 18,
  },
  {
    id: 'juazeiro',
    name: 'Juazeiro do Norte',
    region: 'Cariri',
    city: 'Juazeiro do Norte',
    image: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=85',
    description: 'Fé, xilogravura e a força criativa do povo do Cariri.',
    longDescription: 'Romarias, literatura de cordel, mestres populares e oficinas de criação formam um território cultural singular, moldado pela fé e pela inventividade sertaneja.',
    tags: ['Fé', 'Cordel', 'Cultura popular'],
    photos: 27,
  },
];

export const stories = [
  {
    id: 'maria-rendeira',
    person: 'Dona Maria',
    role: 'Rendeira há 48 anos',
    place: 'Canoa Quebrada',
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=900&q=85',
    excerpt: 'Cada ponto da renda guarda o tempo, a conversa e a memória de quem ensinou.',
    text: 'Dona Maria aprendeu a fazer renda ainda menina, observando as mãos da mãe. Hoje, reúne vizinhas na varanda de casa para trabalhar, conversar e ensinar às mais jovens um ofício que atravessa gerações. Para ela, a renda não é apenas uma peça: é um mapa afetivo da comunidade.',
    readTime: '4 min',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    videoCaption: 'Vídeo demonstrativo com trilha de áudio para validar o player.',
  },
  {
    id: 'seu-raimundo',
    person: 'Seu Raimundo',
    role: 'Mestre da cultura popular',
    place: 'Juazeiro do Norte',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=85',
    excerpt: 'O cordel chega primeiro pelo ouvido; depois a palavra encontra o papel.',
    text: 'Entre versos, matrizes e histórias de feira, Seu Raimundo mantém vivo um repertório aprendido com mestres do Cariri. Sua oficina recebe estudantes e viajantes, sempre com a mesma ideia: cultura só permanece quando circula.',
    readTime: '5 min',
  },
  {
    id: 'lia-musica',
    person: 'Lia Ferreira',
    role: 'Musicista e produtora',
    place: 'Fortaleza',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=85',
    excerpt: 'A cidade também canta quando a gente cria espaços para escutar.',
    text: 'Lia percorre bairros de Fortaleza registrando sonoridades e promovendo encontros entre artistas independentes. Seu trabalho conecta memória, formação e novos palcos para a música feita no Ceará.',
    readTime: '3 min',
  },
];

export const events = [
  { id: 'estacao', day: '24', month: 'JUL', title: 'Sons do Ceará', place: 'Estação das Artes', city: 'Fortaleza', time: '19:00', category: 'Música', free: true },
  { id: 'feira', day: '27', month: 'JUL', title: 'Feira de Artes e Saberes', place: 'Praça da Matriz', city: 'Guaramiranga', time: '09:00', category: 'Cultura popular', free: true },
  { id: 'cordel', day: '02', month: 'AGO', title: 'Encontro de Cordelistas', place: 'Centro Cultural do Cariri', city: 'Crato', time: '16:00', category: 'Literatura', free: true },
  { id: 'cinema', day: '09', month: 'AGO', title: 'Cinema na Falésia', place: 'Praça dos Pescadores', city: 'Aracati', time: '18:30', category: 'Cinema', free: true },
  { id: 'teatro', day: '16', month: 'AGO', title: 'Mostra de Teatro Serrano', place: 'Teatro Municipal', city: 'Guaramiranga', time: '18:00', category: 'Teatro', free: false },
];
